version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: blog-db
    restart: always
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: blog-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blogdb?useSSL=false&serverTimezone=Asia/Tokyo
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db

volumes:
  db-data:
